name: Bug Report
description: Report a bug in the project
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:    
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Blocker
        - Critical
        - Major
        - Minor
        - Trivial
    validations:
      required: true
      
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Descriptions
      description: Describe the steps to reproduce the behavior
      value: |
        **Steps to Reproduce:**
        1. Go to 
        2. Click on 
        
        **Expected Behavior:**
        
        **Actual Behavior:**

        **Thread ID:**
        **Trace ID:**
        **Logs:**
    validations:
      required: true

  - type: markdown
    attributes:
      value: "<br>"
  - type: markdown
    attributes:
      value: "---"    
  - type: markdown
    attributes:
      value: "### Environment"
      
  - type: input
    id: build_info
    attributes:
      label: Build Information
      placeholder: e.g. https://github.com/org/repo/actions/runs/1234567890, ios 1.0(build 105), etc.
    validations:
      required: false
      
  - type: input
    id: device_type
    attributes:
      label: Device Type
      description: "Enter device type(s) separated by commas"
      placeholder: "Mac, iPhone, Android Phone"
    validations:
      required: true
      
  - type: input
    id: browser_app
    attributes:
      label: Browser / App
      description: "Enter browser or app name"
      placeholder: "Chrome, Safari, App"
        
  - type: input
    id: os_version
    attributes:
      label: "OS / App version"
      placeholder: "iOS 26, chrome: 141.0.7390.77, etc."    

